# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Bydgoszcz IT Conference 2018"
shortTitle: "bITconf2018"
email: "kontakt@bitconf.pl"
description: "Bydgoska, wielościeżkowa, cykliczna konferencja techniczna."
baseurl: "/bITconf"
url: "http://ITKontekst.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "ITKontekst.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "IT Kontekst"
organizerAlternateName: "IT Kontekst Wojciech Oczkowski"
organizerDescription: "Outsourcing, szkolenia, projekty IT"
organizerEmail: "kontakt@bitconf.pl"
organizerLogo: "/img/seo/itkontekst.jpg"
organizerLink: "http://itkontekst.pl/"

# Head
metaKeywords: "event, konferencja, Bydgoszcz, it, java, cloud, programowanie, aws, azzure, google, JUG, datacenter, meetup"
twitterAccount: "@bITconf_pl"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "mailto:kontakt@bitconf.pl"
c4sponsorsUrl: "mailto:kontakt@bitconf.pl"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Strona Główna"}
 - {permalink: "/blog/", text: "O Konferencji"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Prelegenci"}
 - {permalink: "/team/", text: "Organizatorzy"}
 - {permalink: "/logistics/", text: "Logistyka"}
bottomNavigationLinks:
 - {link: "https://www.konfeo.com/", text: "Kup bilet"}
rightNavigationButtons:
 - {link: "https://www.konfeo.com/", text: "Kup bilet"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "bITconf 2018 - <typeout>"
eventDate: "14 Września 2018"
typeoutTextValues: '"", "a bit of Java",  "", "a bit of Cloud", "", "a lot of Fun"'
typeoutFallback: "Java and Cloud"
heroButtons:
 - {permalink: "/#tickets", text: "Kup bilet"}

# About Block
aboutTitle: "O Konferencji"
aboutBlock:
 - {title: "Java", image: "conference.jpg", text: "Ścieżka poświęcona programowaniu w języku Java" }
 - {title: "Cloud", image: "workshop.jpg", text: "Ściezka poświęcona technologiom Cloud computing" }
 - {title: "Networking", image: "hackathon.jpg", text: "Przestrzeń wymiany doświadczeń" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "uczestników", detail: "z Bydgoszczy i nie tylko"}
 - {count: "1", specialCharacter: "", info: "dzień", detail: "niezapomnianych wrażeń"}
 - {count: "12", specialCharacter: "+", info: "prelegentów", detail: "z kraju i zagranicy"}
 - {count: "2", specialCharacter: "", info: "równoległe ścieżki", detail: "oraz mnóstwo przestrzeni do wymiany doświadczeń"}

# Latest News Block
latestNewsTitle: "Najnowsze wiadomości"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Najlepsi prelegenci"
rockstarSpeakersButtonText: "Zobacz wszystkich"

# Location Block
locationBlockTitle: "Miejsce konferencji"
eventLocationName: "Hotel HolidayIn"
eventLocationLink: "https://holiday.hgb.com.pl/"
eventStreetAddress: "ul. Grodzka 36"
eventAddressLocality: "Bydgoszcz"
eventAddressLocalityRegion: "Bydgoszcz"
eventPostalCode: "85-109"
eventAddressCountry: "Polska"
eventStartTime: "2018-09-14T09:00"
eventDoorTime: "08:00"
eventEndTime: "2018-09-14T17:00"
eventPlaceCoordinates: "53.121307, 18.00578"
mapCenterCoordinates: "53.121307, 18.00578"
mapMobileCenterCoordinates: "53.121307, 18.00578"

# Venue Block
venueBlockTitle: "Lokalizacja"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Hotel HolidayIn"
venueFeatures: ["2 przestronne sale konferencyjne", "Wysokiej klasy sprzęt Audio/Video", "Swobodna przestrzeń networkingowa" ]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Najnowsze wiadomości"
twitterHashTag: "bITconf_pl"
twitterFeed: "#"

# Partners Block
organizersTitle: "Organizatorzy"
partnersTitle: "Sponsorzy"
partnersC4sponsorsButton: "Zostań sponsorem"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "#"
subscribeInfo: ""

# Tickets Block
ticketsTitle: "Ceny wejściówek"
ticketsInfo: "Wejściówka obejmuje uczestnictwo we wszystkich sesjach konferencji, lunch oraz przerwy kawowe"
ticketsOffers:
 -
  name: "Early Bird"
  price: "149"
  priceCurrency: "PLN"
  ticketsNumber: "100"
  ribbon: "-25%"
  buyButtonLink: "https://konfeo.pl/"
  buyButtonText: "Kup teraz"
  ticketContentList: ["Java", "Cloud", "Networking"]
  validFrom: "2018-05-01T00:00"
  validThrough: "2018-05-31T23:59"
 -
  name: "Cena podstawowa"
  price: "199"
  priceCurrency: "PLN"
  ticketsNumber: "50"
  featured: true
  buyButtonLink: "https://konfeo.pl/"
  buyButtonText: "Kup teraz"
  ticketContentList: ["Java", "Cloud", "Networking"]
  validFrom: "2018-06-01T00:00"
  validThrough: "2018-06-30T23:59"
  disabled: true
 -
  name: "Last Minute"
  price: "249"
  priceCurrency: "PLN"
  ticketsNumber: "50"
  ribbon: "+25%"
  buyButtonLink: "https://konfeo.pl/"
  buyButtonText: "Kup teraz"
  additionalInfo: "Nie czekaj do końca liczba miejsc limitowana"
  ticketContentList: ["Java", "Cloud", "Networking"]
  validFrom: "2018-07-01T00:00"
  validThrough: "2018-09-10T23:59"
  disabled: true
  soldOut: false
  soldOutText: "Wyprzedane"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=bITconf_pl", icon: "twitter"}
 - {link: "https://www.facebook.com/BITconf-355356228308591/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://bydgoszcz.jug.pl", text: "bydgoscz.jug.pl"}
   - {link: "https://www.meetup.com/Cloud-Datacenter-User-Group-Bydgoszcz/", text: "Cloud and Datacenter User Group Bydgoszcz"}
   - {link: "http://itkontekst.pl", text: "IT Kontekst"}
   - {link: "http://symentis.pl", text: "Symentis"}
 -
  title: "Kontakt"
  links:
   - {link: "mailto:kontakt@bitconf.pl", text: "kontakt@bitconf.pl"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Najnowsze informacje"
blogCommentsEnabled: false
discusShortName: "bITconf"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Organizatorzy"
aboutUs: ""

# Logistics Find Way Block
findWayTitle: "Jak do nas dotrzeć"
findWayDistance: "Odległość"
findWayDriving: "Samochodem"
findWayWalking: "Pieszo"
findWayBicycling: "Rowerem"
findWayTransit: "Transportem publicznym"
findWayFindFlight: "Znajdź lot"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Jak dotrzeć"
directionDetailsCards:
 - {title: "Z lotniska", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Transportem publicznym", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
directionDetailsWideCards:
 -
  title: "Pytania?"
  subCards:
   -
    title: "Co zabrać?"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Rejestracja"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Inne"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Warsztaty"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Szczegóły warsztatów"
hackathonRows:
 - {title: "AWS", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "OVH", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Azure", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
